---
- hosts: aws
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
    - name: create file if it doesn't exist
      file:
        state: touch
        path: /var/www/html/index.html
    - name: ??
      lineinfile:
        state: present
        dest: /var/www/html/index.html
        line: Hostname={{ ansible_hostname }}
