---
- hosts: aws
  become: yes
  tasks:
    - name: Install mysql server
      yum: name=mysql-server state=latest
      ignore_errors: yes
      register: there
      tags:
        - packages
    - name: start mysql if there
      service: name=mysqld state=started
      register: running
      tags:
        - tags:
          - startup 
